version: "3.4"

services:
  cwall-web:
    image: cwall-docker
    build:
      context: .
      dockerfile: ./Dockerfile
    depends_on:
      - postgres
    environment:
      NEXT_PUBLIC_CLERK_PUBLISHABLE_KEY: ${NEXT_PUBLIC_CLERK_PUBLISHABLE_KEY}
      CLERK_SECRET_KEY: ${CLERK_SECRET_KEY}
      DATABASE_URL: ${DATABASE_URL}
    ports:
      - 3001:3001

  postgres:
    image: "postgres"
    environment:
      POSTGRES_USER: ${POSTGRES_USER}
      POSTGRES_PASSWORD: ${POSTGRES_PASSWORD}
      POSTGRES_DB: "cwall"
    ports:
      - "5432:5432"
    volumes:
      - ./postgres-data:/var/lib/postgresql/data

volumes:
  postgres-data:
