# Generated by Django 5.0.2 on 2024-02-09 05:45

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("backend", "0001_initial"),
    ]

    operations = [
        migrations.AlterField(
            model_name="image",
            name="image_file",
            field=models.ImageField(upload_to="uploads/"),
        ),
    ]
