name: CWALL CICD

on:
  push:
    branches: ["main"]

jobs:
  build:
    runs-on: self-hosted

    strategy:
      matrix:
        node-version: [20.x]
    env:
      CLERK_SECRET_KEY: ${{ secrets.CLERK_SECRET_KEY }}
      DATABASE_URL: ${{ secrets.DATABASE_URL }}
      NEXT_PUBLIC_CLERK_PUBLISHABLE_KEY: ${{ secrets.NEXT_PUBLIC_CLERK_PUBLISHABLE_KEY }}
    steps:
      - uses: actions/checkout@v3
      - name: Use Node.js ${{ matrix.node-version }}
        uses: actions/setup-node@v3
        with:
          node-version: ${{ matrix.node-version }}
          cache: "npm"
      - run: npm ci
      - name: Create .env file
        run: |
          echo "CLERK_SECRET_KEY=${{ secrets.CLERK_SECRET_KEY }}" > $HOME/actions-runner/_work/cwall-publisher/cwall-publisher/.env
          echo "DATABASE_URL=${{ secrets.DATABASE_URL }}" >> $HOME/actions-runner/_work/cwall-publisher/cwall-publisher/.env
          echo "NEXT_PUBLIC_CLERK_PUBLISHABLE_KEY=${{ secrets.NEXT_PUBLIC_CLERK_PUBLISHABLE_KEY }}" >> $HOME/actions-runner/_work/cwall-publisher/cwall-publisher/.env
        shell: bash
      - run: npm run build --if-present
      - run: echo "${{ secrets.ROOT_PWD }}"  | sudo -S systemctl restart cwall.service
