name: CWALL CICD

on:
  push:
    branches: ["main"]

jobs:
  build:
    runs-on: self-hosted

    strategy:
      matrix:
        node-version: [20.x]
    env:
      CLERK_SECRET_KEY: ${{ secrets.CLERK_SECRET_KEY }}
      DATABASE_URL: ${{ secrets.DATABASE_URL }}
      NEXT_PUBLIC_CLERK_PUBLISHABLE_KEY: ${{ secrets.NEXT_PUBLIC_CLERK_PUBLISHABLE_KEY }}
    steps:
      - name: clear cache
        run: echo "${{ secrets.ROOT_PWD }}" | sudo -S rm -rf $HOME/actions-runner/_work/cwall-publisher/cwall-publisher/.next
      - uses: actions/checkout@v3
      - uses: oven-sh/setup-bun@v1
        with:
          bun-version: latest
      - run: bun i
      - name: Create .env file
        run: |
          echo "CLERK_SECRET_KEY=${{ secrets.CLERK_SECRET_KEY }}" >> $HOME/actions-runner/_work/cwall-publisher/cwall-publisher/.env
          echo "DATABASE_URL=${{ secrets.DATABASE_URL }}" >> $HOME/actions-runner/_work/cwall-publisher/cwall-publisher/.env
          echo "NEXT_PUBLIC_CLERK_PUBLISHABLE_KEY=${{ secrets.NEXT_PUBLIC_CLERK_PUBLISHABLE_KEY }}" >> $HOME/actions-runner/_work/cwall-publisher/cwall-publisher/.env
        shell: bash
      - run: bun --bun run build
      - run: echo "${{ secrets.ROOT_PWD }}"  | sudo -S systemctl restart cwall.service
